var _____WB$wombat$assign$function_____=function(name){return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name))||self[name];};if(!self.__WB_pmw){self.__WB_pmw=function(obj){this.__WB_source=obj;return this;}}{
let window = _____WB$wombat$assign$function_____("window");
let self = _____WB$wombat$assign$function_____("self");
let document = _____WB$wombat$assign$function_____("document");
let location = _____WB$wombat$assign$function_____("location");
let top = _____WB$wombat$assign$function_____("top");
let parent = _____WB$wombat$assign$function_____("parent");
let frames = _____WB$wombat$assign$function_____("frames");
let opens = _____WB$wombat$assign$function_____("opens");
var Reporting=Reporting?Reporting:new Object();Reporting.Constants=Reporting.Constants?Reporting.Constants:new Object();Reporting.Constants.DTV_REPORTING_DATA_SENT="dtv:ReportingPageDataSent";Reporting.Utils=Reporting.Utils?Reporting.Utils:new Object();Reporting.Utils.addUniqueItemToArray=function(e,d){if(d){var c=false;for(var b=0,a=e.length;b<a;b++){c=(e[b]===d);if(c){break}}if(!c){e[e.length]=d}}};Reporting.Utils.isBlank=function(a){return(a==undefined||a==null||(typeof(a)=="string"&&a.replace(/\s/g,"").length==0))
};Reporting.UserActionManager=function(){function a(){var b={FORGOT_PASSWORD:{handler:this.reportGenericAjaxRequest,config:{events:"event43",successEvents:"event42",linkName:"Forgot Password"}},FORGOT_EMAIL:{handler:this.reportGenericAjaxRequest,config:{events:"event41",successEvents:"event40",linkName:"Forgot Email"}},SCHEDULE_INSTALLATION:{handler:this.reportScheduleInstall,config:{linkName:"Schedule Install"}},ORDER_PPV:{handler:this.reportOrderPpv,config:{linkName:"Order PPV"}},ORDER_DOD:{handler:this.reportOrderDod,config:{linkName:"Order DOD"}},USER_PREFERENCE_CHANGE:{handler:this.reportUserPrefChange,config:{linkName:"User Preferences Change"}},USER_CHANGE_PASSWORD:{handler:this.reportUpdateAccountInfo,config:{events:"event16",successEvents:"event32",linkName:"Change Password"}},USER_UPDATE_SECURITY_QUESTION:{handler:this.reportUpdateAccountInfo,config:{events:"event16",successEvents:"event32",linkName:"Security Question Update"}},PRE_CREDIT_CHECK:{handler:this.reportPepodCheckout,config:{linkName:"PEPOD Checkout"}},CART_UPDATES:{handler:this.reportPepodCartUpdates,config:{linkName:"PEPOD Cart Update"}},CHECKOUT_START:{handler:this.reportPepodCheckoutFlow,config:{linkName:"PEPOD Checkout"}},LOCATION_DATA_SET:{handler:this.reportZipcodeData,config:{linkName:"ZIPCODE"}},CLOSING_OFFER:{handler:this.reportClosingOffer,config:{linkName:"CLOSING OFFER"}},EMAIL_CART:{handler:this.reportEmailCart,config:{linkName:"Email Cart"}},CLEAR_CART:{handler:this.reportClearCart,config:{linkName:"Clear Cart"}},ONETIME_PAY:{handler:this.reportOneTimePay,config:{linkName:"One Time Pay"}},AUTOBILL_PAY:{handler:this.reportAutoBillPay,config:{linkName:"Auto Pay"}},CANCEL_PAY:{handler:this.reportCancel,config:{linkName:"Cancel"}}};
this.handleLightbox=function(c){this.reportLightboxOpened(Event.element(c),c.memo)};this.handleAjaxReporting=function(c){if(c.memo&&c.memo.json){var n=c.memo.json;var f=[];var l={errors:"",topMessages:"",rightMessage:"",messages:""};for(var k in n){if(k in l){f=f.concat(n[k])}}this.reportMessageKeys(f,Reporting.pageName);if(n.reportingData){var e=n.reportingData;for(var h=0,g=e.length;h<g;h++){var m=e[h];if(m){var d=b[m.action];if(d&&d.handler&&(d.handler instanceof Function)){d.handler.apply(this,new Array(d.config,m))
}else{console.log("No config or handler was found for action: "+m.action)}}}}}};this.handleAccordionOpened=function(e){var f=Event.element(e).previous();if(f==null||f.innerHTML==null||f.innerHTML.length==0){return}var c="Tab - "+Reporting.pageName+" :: "+f.innerHTML;var d=this.getCleanReportingObject();if(f.innerHTML=="Subscriptions"||f.innerHTML=="Programming Interests"||f.innerHTML=="Advanced Features Interests"||f.innerHTML=="Sports Interests"||f.innerHTML=="International Programming Interests"){d.prop36=f.innerHTML;
d.linkTrackVars="prop36"}if(typeof c!="undefined"&&Reporting.pageName!="English Packages"&&Reporting.pageName!="Spanish Packages"){d.tl(this,"o",c)}};document.observe(Reporting.Constants.DTV_REPORTING_DATA_SENT,(function(){var d={};d[EVENT_LIGHTBOX_RENDERED]=this.handleLightbox;d[Dtv.FormController.EVENTS.SUBMIT_SUCCESS]=this.handleAjaxReporting;d[Dtv.FormController.EVENTS.SUBMIT_FAILURE]=this.handleAjaxReporting;if(Dtv.Behaviors.Accordion){d[$consts("Accordion").EVENTS.ACCORDION_OPENED]=this.handleAccordionOpened
}for(var c in d){document.observe(c,d[c].bind(this))}}).bind(this))}a.prototype={getCleanReportingObject:function(){var b=Reporting.getReportingObject(Reporting.accountId);for(var c in b){if((c.search(/^eVar\d+$/)>=0)||(c.search(/^prop\d+$/)>=0)){b[c]=null}}b.linkTrackEvents=null;b.linkTrackVars=null;b.events=null;b.products=null;if(Reporting.pageReportSent){b.campaign=null;b.prop29=null;b.eVar34=null;b.pageURL=null}return b},reportProductListingView:function(e,b,k,d){e=e?e:null;b=b?b:false;if(e==null){return
}var i="";var c=new String(document.location).indexOf("?genre");var l=new String(document.location).indexOf("?category");var h=document.URL.split("?")[0].split("/").last();var f={"gameLounge.jsp":"Games","ppvMovies.jsp":"PPV Movies","ppvAdult.jsp":"PPV Adult","ppvEvents.jsp":"PPV Events","theGuide.jsp":"EPG Listing","dodMovies.jsp":"DOD Listing"};var j=f[h]!=null?f[h]:"EPG Listing";var g=b?"Carousel":"Listing";if(h==="ppvMovies.jsp"){i="All"}else{if(h==="ppvEvents.jsp"){i="Events"}else{if(h==="ppvAdult.jsp"){i="Adult"
}else{if(h==="theGuide.jsp"){i="EPG"}else{if(h==="dodMovies.jsp"){i="DOD"}else{if(h==="gameLounge.jsp"){i="All"}}}}}}if(c>0){i=document.URL.toQueryParams().genre}else{if(l>0){i=document.URL.toQueryParams().category}}var m=this.getCleanReportingObject();m.linkTrackVars="events,products,prop34,prop35,prop26";m.linkTrackEvents="prodView,event3";m.events="prodView,event3";m.products=";"+e;m.prop34=j+":"+k+"::"+d;m.prop35=i;m.prop26=j;m.tl(this,"o",j)},reportPepodProductView:function(h,i,g,d){if(!g){var f=this.getCleanReportingObject();
var b=Reporting.pageName;if(h!=null){if(h=="cat_cart_prospect_premium"){h="Premium Flyout"}else{if(h=="cat_cart_prospect_sports"){h="Sports Flyout"}else{if(h=="cat_cart_prospect_international"){h="International Flyout"}else{if(h=="cat_cart_prospect_services"){h="Services Flyout"}else{if(h=="cat_cart_prospect_package"){h="Base Package Flyout"}else{if(h=="zipcode"){h="Zip Code"}else{if(h=="emptyCart"){h="Empty Cart"}else{if(h=="gettingStarted"){h="Getting Started"}}}}}}}}}else{h="Receiver Flyout";f.zip=null;
f.state=null}f.overrideLinkTracking=true;f.linkTrackVars="prop41,prop42,prop43,prop26";if(h=="Receiver Flyout"&&(b=="English Packages"||b=="Spanish Packages")){}else{var e="Add to Cart";if(h=="Zip Code"){if(b=="PEPOD - Shopping Cart"){e="Change Zip"}}if(i){b="/DID "+i+"/"+b}f.prop41=b;if(h!="Zip Code"&&h!="Getting Started"&&h!="Empty Cart"){if(h=="Receiver Flyout"&&d){f.prop42="Dependancy Flow";f.prop43=b+" : Dependancy Flow"}else{f.prop42="Edit "+h;f.prop43=b+" : Edit "+h}}else{if(h=="Getting Started"){f.prop42="Order Now";
f.prop43=b+" : Order Now"}else{if(h=="Zip Code"){f.prop42=e;f.prop43=b+" : "+e}}}}f.products=null;if(i){h="/DID "+i+"/"+h}f.prop26=h;f.pageName=h;var c=f.t();if(c){document.write(c)}}},reportChannelsView:function(c){var d=this.getCleanReportingObject();var b=Reporting.pageName;if(c!=null){d.overrideLinkTracking=true;d.linkTrackVars="prop41,prop42,prop43";d.prop41=Reporting.pageName;d.prop42=c.toUpperCase()+" Channels";d.prop43=Reporting.pageName+" : "+c.toUpperCase()+" Channels"}d.tl(this,"o",b)},reportClosingOfferView:function(d){var e=this.getCleanReportingObject();
var b=Reporting.pageName;var c=[];e.linkTrackVars="eVar5,prop38,prop26,events,products";e.linkTrackEvents="event33,scAdd";c[c.length]="event33";c[c.length]="scAdd";e.prop38="Offer Overlay :: Accepted";e.products=d;e.eVar5=d;e.prop26=b;e.events=c.join();e.tl(this,"o",b)},reportPackageChange:function(i,e,f,d,g){var j=this.getCleanReportingObject();var k=[];var b="";var h=Reporting.pageName;j.linkTrackVars="prop26,eVar24,eVar16,eVar20,eVar18,eVar28,prop41,prop42,prop43";j.linkTrackEvents="event14,event63,event65";
if(f!=null&&f.indexOf("/mydirectv/account")>0){b="My Programming";j.prop26=b+": "+i+" Confirmation Flyout";j.pageName=b+": "+i+" Confirmation Flyout"}else{b="Content";j.prop26=i+" Confirmation Flyout";j.pageName=i+" Confirmation Flyout"}j.prop41=h;j.prop42=" Activate";j.prop43=h+" : Activate";j.eVar24=b;k[k.length]="event14";if(e==null){j.eVar20=d;if(i!=null&&i.indexOf("Removal")>0){j.eVar16="remove"}else{j.eVar16="add"}k[k.length]="event65"}else{j.eVar18=d;j.eVar28=g;k[k.length]="event63"}j.events=k.join();
var c=j.t();if(c){document.write(c)}},reportPayBillExt:function(e,b){var f=this.getCleanReportingObject();var d=Reporting.pageName;f.linkTrackVars="prop1,prop2,prop3,prop6,prop7,prop26,eVar10,prop41,prop42,prop43";f.linkTrackEvents="event50,event52";f.prop26=document.URL;f.prop1="My Account";f.prop2="Pay My Bill";f.prop6=e;f.prop7="Existing";f.eVar10="Existing";if(b!=null&&b.indexOf("payExt")!=-1){f.pageName="DIRECTV: Payment Extension";f.prop3="Payment Extension";f.events="event50";f.prop41=d;f.prop42="Payment Extension";
f.prop43=d+" :  Payment Extension"}else{f.pageName="DIRECTV: Payment Notification";f.prop3="Payment Notification";f.events="event52";f.prop41=d;f.prop42="Already Paid";f.prop43=d+" :  Already Paid"}var c=f.t();if(c){document.write(c)}},reportHardwareRequire:function(d,g){var e=this.getCleanReportingObject();var c=Reporting.pageName;var f="";e.linkTrackVars="prop26,eVar24,prop41,prop42,prop43";if(g!=null&&g.indexOf("/mydirectv/account")>0){f="My Programming";e.pageName=f+": Select "+d+" Flyout";e.prop26=f+": Select "+d+" Flyout"
}else{f="Content";e.pageName="Select "+d+" Flyout";e.prop26="Select "+d+" Flyout"}e.prop41=c;e.prop42=" Activate";e.prop43=c+" : Activate";e.eVar24=f;var b=e.t();if(b){document.write(b)}},reportAddressType:function(d){var e=this.getCleanReportingObject();var c=Reporting.pageName;e.linkTrackVars="prop26,prop41,prop42,prop43";if(d!=null){if(d.indexOf("BILLING")!=-1){d="Billing Address"}else{if(d.indexOf("SHIPPING")!=-1){d="Shipping Address"}}}e.pageName="Change "+d;e.prop26="Change "+d;e.prop41=c;e.prop42=" Change";
e.prop43=c+" : Change";var b=e.t();if(b){document.write(b)}},reportGenericAjaxRequest:function(f,c){f=f?f:{};c=c?c:{};if(f){var e=this.getCleanReportingObject();var b=(f.linkName)?f.linkName:Reporting.pageName;var d=f.events.split(",");if(f.successEvents){d=d.concat(f.successEvents.split(","))}e.linkTrackVars="events";e.linkTrackEvents=d.join();e.events=(c.success)?d.join():f.events;if(typeof b!="undefined"){e.tl(this,"o",b)}}},reportOrderPpv:function(e,h){e=e?e:{};h=h?h:{};var g=this.getCleanReportingObject();
var b=(e.linkName)?e.linkName:Reporting.pageName;var d=h.data;if(d){var f=[];g.linkTrackVars="eVar14,eVar15,eVar19,eVar37,eVar30,prop26,events,products";g.linkTrackEvents="purchase,event21,event22";g.eVar37=d.paymentMethod;f[f.length]="event21";var c=document.URL.split("?")[0].split("/").last();g.eVar19=(d.carousel=="true"?"Carousel":"PPV");if(c==="ppvMovies.jsp"){g.eVar14="Movies"}else{if(c==="ppvEvents.jsp"){g.eVar14="Events"}else{if(c==="ppvAdult.jsp"){g.eVar14="Adult"}else{g.eVar14="EPG";g.eVar19="EPG"
}}}g.eVar15=d.billingId;if(h.success){f[f.length]="purchase";f[f.length]="event22";g.products=";"+d.billingId+";1;"+Number(d.price).toFixed(2);g.eVar30="PPV"}else{console.log("Could not add PPV")}g.prop26=b;g.events=f.join();if(typeof b!="undefined"){g.tl(this,"o",b)}}},reportOrderDod:function(e,i){e=e?e:{};i=i?i:{};var g=this.getCleanReportingObject();var b=(e.linkName)?e.linkName:Reporting.pageName;var d=i.data;if(d){var f=[];var h=document.URL.split("?")[0].split("/").last()=="";g.linkTrackVars="eVar14,eVar15,eVar17,eVar19,prop9,prop26,events,products";
g.linkTrackEvents="event68,event69";if(!h){f[f.length]="event68"}var c=document.URL.split("?")[0].split("/").last();g.eVar19=(d.carousel=="true"?"PPV Carousel Listings":"PPV Listings");if(c==="ppvMovies.jsp"){g.eVar14="Movies"}else{if(c==="ppvEvents.jsp"){g.eVar14="Events"}else{if(c==="ppvAdult.jsp"){g.eVar14="Adult"}else{if(c==="dodMovies.jsp"){g.eVar14="DOD";if(d.carousel=="true"){g.eVar19="DOD Carousel Listings"}else{g.eVar19="DOD Listings"}}else{g.eVar14="EPG";if(d.carousel=="true"){g.eVar19="EPG Carousel Listings"
}else{g.eVar19="EPG Listings"}}}}}g.eVar15=d.programId;if(d.record=="false"){if(c==="dodMovies.jsp"){g.prop9="Add to Queue"}else{if(i.success){g.prop9="Record if possible::Success"}else{g.prop9="Record if possible::Attempt"}}}else{if(c==="dodMovies.jsp"){g.prop9="Add to Top of Queue"}else{g.prop9="Definitely record"}}if(i.success){if(!h){f[f.length]="event69"}g.products=";"+d.programId+";1"}else{console.log("Could not add DOD")}g.prop26=b;g.events=f.join();if(typeof b!="undefined"){g.tl(this,"o",b)
}}},reportUserPrefChange:function(d,h){if(h){var g=this.getCleanReportingObject();var c=(d.linkName)?d.linkName:Reporting.pageName;var b=h.data.preferenceValue?h.data.preferenceValue:"UNKNOWN";var f=h.data.checked;var e="UNKNOWN";g.prop12=c;g.eVar26=c;if(b){pvArray=b.split("_");if(pvArray[0]){if(pvArray[0]=="E"){e="Subscriptions:"}else{if(pvArray[0]=="P"){e="Programming Interests:"}else{if(pvArray[0]=="DTV"){e="Advanced Features Interests:"}else{if(pvArray[0]=="S"){e="Sports Interests:"}else{if(pvArray[0]=="I"){e="International Programming Interests:"
}}}}}g.prop36=e+b+(f=="true"?"::Subscribe":"::Unsubscribe")}}g.linkTrackVars="prop12,prop36,prop26,eVar26";g.linkTrackEvents=null;g.prop26=c;if(typeof c!="undefined"){g.tl(this,"o",c)}}},reportUpdateAccountInfo:function(d,f){if(f){var e=this.getCleanReportingObject();var b=(d.linkName)?d.linkName:Reporting.pageName;e.prop12=b;e.eVar26=b;var c=d.events.split(",");if(d.successEvents){c=c.concat(d.successEvents.split(","))}e.linkTrackVars="prop12,eVar26,prop26,events";e.linkTrackEvents=c.join();e.events=(f.success)?c.join():d.events;
e.prop26=b;if(typeof b!="undefined"){e.tl(this,"o",b)}}},reportScheduleInstall:function(d,g){if(g){var f=this.getCleanReportingObject();var b=(d.linkName)?d.linkName:Reporting.pageName;var c=g.data.reschedule;var h=g.data.pending;c=c?c:"false";h=h?h:"false";var e=((h==="true"&&c!=="true")?"Wizard":"CEPOD")+":"+(g.success?"Success":"Failure");if(c==="true"){f.prop21=e;f.eVar39="Yes"}else{f.prop17=e}f.linkTrackVars="prop17,prop21,prop26,eVar39";f.prop26=b;if(typeof b!="undefined"){f.tl(this,"o",b)}}},reportAvailableDates:function(d,g,f,h){var e=this.getCleanReportingObject();
var c=null;var d=d?d:false;var g=g?g:false;var f=f?f:false;e.events="event61";if(f){e.events="event62"}if(h){e.pageName="/DID "+h+"/Checkout Installation";e.prop26="/DID "+h+"/Checkout Installation"}else{e.pageName="Checkout Installation";e.prop26="Checkout Installation"}e.prop18=(d?"Wizard":"CEPOD")+":"+((!g&&!f)?"Success":"Failure");e.linkTrackVars="prop18,prop26,events";e.linkTrackEvents="event61,event62";var b=e.t();if(b){document.write(b)}},reportMessageKeys:function(c,b){var d=this;b="Message Key - "+b;
if(c){c.each(function(g){var e=g;if(g.search(/@key:\s([\S]+)\s/)>=0){e=RegExp.$1}else{return}var f=d.getCleanReportingObject();f.linkTrackVars="prop37,eVar42,events";f.linkTrackEvents="event30";f.eVar42=e;f.prop37=e;f.events="event30";f.tl(d,"o",b)})}},reportPepodCartUpdates:function(c,d){if(d){var h=this.getCleanReportingObject();var j=[];var g=Reporting.pageName;var f=d.data.type;if(f!="Order Module"){h.eVar3="Cart"}else{h.eVar3="Content"}if(f!=null){if(f=="cat_prog_premium_pickone"||f=="cat_prog_special"){f="Premium Flyout"
}else{if(f=="cat_prog_sports"){f="Sports Flyout"}else{if(f=="cat_prog_international"){f="International Flyout"}else{f="Receiver Flyout"}}}}else{if(g=="English Packages"||g=="Spanish Packages"){f="Receiver Flyout"}else{f="Base Package Flyout"}}h.linkTrackVars="eVar3,eVar30,prop26,products,events";h.eVar30="Wizard";if(d.data.add){var i=d.data.addSku;j[j.length]=d.data.add;h.products=";"+i;if(i.indexOf("6004")>0){j[j.length]="scOpen"}if(i.indexOf("B000002072")>=0||i.indexOf("R000001151")>=0){f="Services Flyout"
}h.events=j.join();if(d.data.dealerId!=null){f="/DID "+d.data.dealerId+"/"+f}h.pageName=f;var b=h.t();if(b){document.write(b)}}if(d.data.remove){var e=d.data.removalSku;h.products=";"+e;if(e.indexOf("B000002072")>=0||e.indexOf("R000001151")>=0){f="Services Flyout"}h.events="scRemove";if(d.data.dealerId!=null){f="/DID "+d.data.dealerId+"/"+f}h.prop26=f;h.pageName=f;var b=h.t();if(b){document.write(b)}}}},reportPepodCheckout:function(d,e){if(e){var i=this.getCleanReportingObject();var j=[];var f="";
var g="";var b="";var h=Reporting.pageName;if(e.data.creditCheck=="yes"){i.prop16="Yes"}else{i.prop16="No"}if(e.data.creditFee!=null){i.eVar8=e.data.creditFee}i.linkTrackVars="eVar5,prop41,prop42,prop43,eVar8,prop16,prop38,prop26,events,products";i.linkTrackEvents="event34,scRemove";if(e.data.mode!=null&&e.data.mode=="checkOutAddress"){f="Checkout Account Info";g="Checkout Continue";b="Checkout Address"}else{f="Checkout Address";g="Pre Credit Check";b="Checkout Address"}if(e.data.dealerId!=null){f="/DID "+e.data.dealerId+"/"+f;
b="/DID "+e.data.dealerId+"/"+b}i.prop26=f;i.pageName=f;if(e.success){i.overrideLinkTracking=true;i.prop41=b;i.prop42=g;i.prop43=b+" : "+g}if(e.data.removeClosingOffer!=null&&e.data.removeClosingOffer=="true"){j[j.length]="event34";j[j.length]="scRemove";i.products=e.data.closingOfferId;i.eVar5=e.data.closingOfferId;i.prop38="Offer Overlay :: Removed :: Bad Credit"}i.events=j.join();var c=i.t();if(c){document.write(c)}}},reportPepodCheckoutFlow:function(e,g){if(g){var f=this.getCleanReportingObject();
var b=Reporting.pageName;f.linkTrackVars="prop26,eVar30,events,products";f.linkTrackEvents="event36,scCheckout";var d="Checkout Payment";if(g.data.mode=="Checkout Address"){f.events="scCheckout";d="Checkout Address";var h=g.data.skuId;f.products=";"+h;f.eVar30="Wizard"}else{if(g.data.emailOpt){f.events="event36"}}if(g.data.dealerId!=null){d="/DID "+g.data.dealerId+"/"+d}f.prop26=d;f.pageName=d;var c=f.t();if(c){document.write(c)}}},reportZipcodeData:function(e,g){if(g){var f=this.getCleanReportingObject();
var b=Reporting.pageName;var d="Zip Code";f.state=g.data.state;f.zip=g.data.zip;f.eVar47=g.data.dma;if(g.data.dealerId!=null){d="/DID "+g.data.dealerId+"/"+d}f.pageName=d;f.prop26=d;f.linkTrackVars="prop26,eVar47,state,zip,events";var c=f.t();if(c){document.write(c)}}},reportClosingOffer:function(e,i){if(i){var g=this.getCleanReportingObject();var f=[];var b=Reporting.pageName;var d="PEPOD - Shopping Cart";if(i.data.requestPage){var h=i.data.requestPage;if(h.indexOf("lightboxCheckoutUserAddress.jsp")>0){h="Checkout Address"
}else{if(h.indexOf("lightboxCheckoutUserLogin.jsp")>0){h="Checkout  Account Info"}else{if(h.indexOf("lightboxCheckoutPayment.jsp")>0){h="Checkout Payment"}}}f[f.length]="scView"}g.linkTrackVars="prop26,events";g.linkTrackEvents="scView";g.events=f.join();if(i.data.dealerId!=null){d="/DID "+i.data.dealerId+"/"+d}g.prop26=d;g.pageName=d;var c=g.t();if(c){document.write(c)}}},reportEmailCart:function(c,e){if(e){var d=this.getCleanReportingObject();var b=Reporting.pageName;d.events="event13";d.linkTrackVars="prop26,events";
d.prop26=b;d.tl(this,"o",b)}},reportClearCart:function(d,f){if(f){var e=this.getCleanReportingObject();var g=f.data.referer;if(g!=null){var c="DIRECTV: Account Overview";if(g.indexOf("packages/base_packages.jsp?language=SPANISH")>0){c="DIRECTV: Spanish Packages"}else{if(g.indexOf("packages/base_packages.jsp")>0){c="DIRECTV: English Packages"}}e.pageName=c;var b=e.t();if(b){document.write(b)}}}},reportOneTimePay:function(e,h){if(h){var g=this.getCleanReportingObject();var b=Reporting.pageName;var f=[];
var d="DIRECTV: Pay Your Bill";var i=h.data.status+"_"+h.data.paymentType+"_"+h.data.amountType;if(h.data.enroll!=null){g.eVar17=h.data.status+"_"+h.data.paymentType+h.data.enroll;f[f.length]="event18"}g.eVar37=i;g.eVar10="Existing";g.prop6=h.data.acctNumber;g.prop7="Existing";f[f.length]="event48";g.events=f.join();g.linkTrackVars="prop1,prop2,prop3,prop4,prop6,prop7,prop41,prop42,prop43,eVar10,eVar17,eVar37,events";g.linkTrackEvents="event18,event48";g.prop1="My Account";g.prop2="My Account:Pay Bill";
g.prop3="My Account:Pay Bill:One-Time";g.prop4="My Account:Pay Bill:One-Time:Review Your Info";g.prop41=d;g.prop42="Continue";g.prop43=d+" :  Continue";g.prop26=document.URL;g.pageName=d;var c=g.t();if(c){document.write(c)}}},reportAutoBillPay:function(e,g){if(g){var f=this.getCleanReportingObject();var b=Reporting.pageName;var d="DIRECTV: Auto Bill Pay";var h=g.data.status+"_"+g.data.paymentType+"_ABP"+g.data.enroll;f.eVar17=h;f.eVar10="Existing";f.prop6=g.data.acctNumber;f.prop7="Existing";f.events="event18";
f.linkTrackVars="prop1,prop2,prop3,prop4,prop6,prop7,prop41,prop42,prop43,eVar10,eVar17,events";f.linkTrackEvents="event18";f.prop1="My Account";f.prop2="My Account:Pay Bill";f.prop3="My Account:Pay Bill:ABP";f.prop4="My Account:Pay Bill:ABP:Review Your Info";f.prop41=d;f.prop42="Continue";f.prop43=d+" :  Continue";f.prop26=document.URL;f.pageName=d;var c=f.t();if(c){document.write(c)}}},reportCancel:function(d,g){if(g){var e=this.getCleanReportingObject();var c=Reporting.pageName;var f=g.data.source;
if(f!=null){if(f.indexOf("payment/myPayBill.jsp")>0){c="DIRECTV: Pay Your Bill"}else{if(f.indexOf("account/myAccountProfile.jsp")>0){c="DIRECTV: Account Profile"}else{if(f.indexOf("account/myAccount.jsp")>0){c="DIRECTV: Account Details"}else{if(f.indexOf("payment/viewStatements.jsp")>0){c="Paperless Billing"}}}}}e.pageName=c;var b=e.t();if(b){document.write(b)}}},reportSummarySearchResults:function(c,e){var b=Reporting.pageName;var d=this.getCleanReportingObject();d.linkTrackVars="eVar1,prop46,prop26,events";
d.linkTrackEvents="event1,event2";d.eVar1=c;d.prop46=c;d.prop26=b;d.events=((e)?"event1":"event2");if(typeof b!="undefined"){d.tl(this,"o",b)}},reportModuleSearch:function(c,b,e){var d=this.getCleanReportingObject();d.linkTrackVars="prop47";d.linkTrackEvents="";d.prop47=c+" : "+b+" :: "+((e)?"Search Results":"Null Results");d.tl(this,"o",Reporting.pageName)},reportLightboxOpened:function(e,h){h=h?h:{};var i=e.select(".lb-header");var c="";if(i&&i.length>0){c=i[0].innerHTML}var b=h.pageName?h.pageName:c;
var d="Lightbox - "+b;var g=this.getCleanReportingObject();g.linkTrackVars="events";g.tl(this,"o",d);var f=[];e.select("ul.js_message_content li:not([class=hidden])").each(function(j){f[f.length]=j.innerHTML});this.reportMessageKeys(f,b)},reportFlashLinkData:function(f,e,d){var c=this.getCleanReportingObject();var b=Reporting.pageName;c.overrideLinkTracking=true;c.linkTrackVars="prop41,prop42,prop43,prop44";c.prop41=b;c.prop42=f;c.prop43=b+" | "+f;c.prop44=d;c.tl(this,"o",b);c.overrideLinkTracking=false
},reportPageMessageKeys:function(){var b=["selfcare-message","loginMessageDiv","checkout-error"];var c=[];b.each(function(d){if($(d)){$(d).select("ul.js_message_content li:not([class=hidden])").each(function(e){c[c.length]=e.innerHTML});$(d).select("span.supercast-error-text").each(function(e){c[c.length]=e.innerHTML});$(d).select("span.supercast-warn-text").each(function(e){c[c.length]=e.innerHTML});$(d).select("span.supercast-info-text").each(function(e){c[c.length]=e.innerHTML})}});if(c.length>0){this.reportMessageKeys(c,Reporting.pageName)
}}};return new a()}();document.fire("dtv:ReportingUserManagerLoaded");
}

/*
     FILE ARCHIVED ON 14:17:58 Jul 10, 2010 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 13:59:32 Apr 02, 2026.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 2.381
  exclusion.robots: 1.633
  exclusion.robots.policy: 1.618
  esindex: 0.015
  cdx.remote: 54.887
  LoadShardBlock: 565.656 (3)
  PetaboxLoader3.datanode: 140.526 (4)
  PetaboxLoader3.resolve: 702.495 (2)
  load_resource: 615.537
*/